export default[
    {
        id:1,
        image:"./image/tshirt.jpg",
        type:"T-SHIRT",
        price:500,
        tolqunatity:10,
    },
    {
        id:2,
        image:"./image/jeans.jpg",
        type:"JEANS",
        price:800,
        tolqunatity:12,
    },
    {
        id:3,
        image:"./image/tshirt.jpg",
        type:"T-SHIRT",
        price:500,
        tolqunatity:10,
    },
    {
        id:4,
        image:"./image/jeans.jpg",
        type:"JEANS",
        price:800,
        tolqunatity:12,
    },
    {
        id:5,
        image:"./image/tshirt.jpg",
        type:"T-SHIRT",
        price:500,
        tolqunatity:10,
    },
    {
        id:6,
        image:"./image/jeans.jpg",
        type:"JEANS",
        price:800,
        tolqunatity:12,
    }
]